fix(Parameters): add support for custom connection
BLSQ/openhexa-sdk-python pull request #116
Opened 2024-01-22 13:38 UTC by cheikhgwane

2024-01-22 15:27 UTC, pvanliefland requested changes
Hi @cheikhgwane , I think there's still an issue, see comment.

Also, we should add a test for this.

2024-01-22 15:27 UTC, pvanliefland commented on openhexa/sdk/pipelines/parameter.py
@cheikhgwane I can't add my comment on that specific line but could you check lines 301-303 (def `expected_type` for the`CustomConnectionType` class? It doesn't seem right.

2024-01-22 16:34 UTC, cheikhgwane commented on openhexa/sdk/pipelines/parameter.py
Oh yes it should return CustomConnectionType

2024-01-23 13:16 UTC, pvanliefland approved these changes
LGTM!

2024-01-23 13:16 UTC, merged