feat: add a retry mechanism for API call
BLSQ/openhexa-sdk-python pull request #166
Opened 2024-06-18 14:44 UTC by cheikhgwane

Add a retry mechanism for the communication with the API

2024-06-18 14:49 UTC, qgerome requested changes
You need to check the `requests` documentation to implement a retry mechanism. No need to implement something custom. We can do it at this level directly

2024-06-18 16:32 UTC, cheikhgwane commented
> You need to check the `requests` documentation to implement a retry mechanism. No need to implement something custom. We can do it at this level directly

I've added a httpClient based on Session and Retry object. I've also used the default status_forcelist. Let me know if I need to add/remove status code from that list

2024-06-25 10:23 UTC, qgerome requested changes

2024-06-25 10:23 UTC, qgerome commented on openhexa/sdk/utils.py
> +def retry(*args, **kwargs):
This can be removed.

2024-06-25 10:23 UTC, qgerome commented on openhexa/utils/HttpClient.py
> +httpClient = requests_builder()
I would not export this but more the `requests_builder`

2024-06-25 10:23 UTC, qgerome commented on openhexa/utils/HttpClient.py
> +def requests_builder(
```suggestion
def create_requests_session(
```

2024-06-27 09:45 UTC, qgerome requested changes

2024-06-27 09:45 UTC, qgerome commented on openhexa/utils/HttpClient.py
> +    session=None,
Why do you accept a `session` here ?

2024-06-27 09:46 UTC, qgerome requested changes

2024-06-27 09:46 UTC, qgerome commented on openhexa/utils/HttpClient.py
This should be renamed "session.py" no ?

2024-06-27 09:48 UTC, cheikhgwane commented on openhexa/utils/HttpClient.py
> +    session=None,
It shouldn't be here thanks!

2024-06-28 08:53 UTC, merged