Feat/pipeline timeout
BLSQ/openhexa-sdk-python pull request #64
Opened 2023-07-31 15:56 UTC by cheikhgwane

Allow user to define timeout value after which the pipeline will be automatically stopped.

2023-08-01 08:38 UTC, pvanliefland requested changes
Hey @cheikhgwane , I think that if we want to specify timeouts through the SDK, we should keep the validation logic in the backend.

Also pinging @yannforget and @qgerome to get their opinion on this. Another option would be to specify timeouts through the web interface.

2023-08-01 08:38 UTC, pvanliefland commented on openhexa/sdk/pipelines/pipeline.py
> +PIPELINE_MAX_TIMEOUT = 43200
I don't think this should be hardcoded here. The max should be handled by the backend.

2023-08-01 08:38 UTC, pvanliefland commented on openhexa/sdk/pipelines/pipeline.py
> +    code: str, *, name: str = None, timeout: int = PIPELINE_MAX_TIMEOUT
I would keep a default of `None` for the timeout and let the backend set the default value.

2023-08-01 08:38 UTC, pvanliefland commented on openhexa/sdk/pipelines/pipeline.py
> +    if timeout > PIPELINE_MAX_TIMEOUT:
Validation should be handled by the backend.

2023-08-01 08:52 UTC, cheikhgwane commented
@pvanliefland Alright, will remove the validation on the sdk (already handled on the backend )

2023-08-01 08:55 UTC, qgerome commented
> Hey @cheikhgwane , I think that if we want to specify timeouts through the SDK, we should keep the validation logic in the backend.
> 
> Also pinging @yannforget and @qgerome to get their opinion on this. Another option would be to specify timeouts through the web interface.

I agree with your comments. We had a discussion with Cheikh and the conclusion was to only implement it on the SDK & backend. The timeout can still be edited in the admin if needed but I would not let the user edit the timeout from the UI in the first version.

2023-08-02 10:00 UTC, pvanliefland approved these changes
LGTM!

2023-08-08 07:24 UTC, merged